const path = require('path');
const fs = require('fs');
const { ensureDir, fileExists, writeFile } = require('./fs-utils');

const GITIGNORE_MARKER = '# Yuva AI - generated native configs';

const GITIGNORE_BLOCK = `
${GITIGNORE_MARKER} (regenerate with: yuva init)
# Source of truth: AGENTS.md + .aiautomations/
CLAUDE.md
.claude/
GEMINI.md
.cursor/rules/yuva-*.mdc
.windsurfrules
.github/copilot-instructions.md
.kilo/
.sourcegraph/
.amazonq/
.continue/
.aider.conf.yml
OLLAMA_INSTRUCTIONS.md
`;

function getBaseTemplate(toolName) {
  return `# Yuva AI - ${toolName} Configuration
<!-- Auto-generated by yuva init. Do not edit — regenerate with: yuva init --force -->

## CRITICAL: Before ANY task
You MUST run \`yuva agent orchestrate\` first. Do NOT start work without it.
Read the JSON output to understand the project state.

## How to load agent instructions
NEVER guess or improvise agent behavior.
Run: \`yuva agent show <name>\` to get the EXACT prompt for any agent.
Follow each agent's instructions completely before moving to the next.

## Agent Selection Guide

| User wants to...        | Run these agents in order                                                     |
|-------------------------|-------------------------------------------------------------------------------|
| Build something new     | \`yuva agent show requirements\` then \`riskassessment\` then \`planning\` then \`execution\` |
| Continue previous work  | \`yuva agent show continuity\` then resume from last point                    |
| Fix a bug / error       | \`yuva agent show debugger\`                                                  |
| Write tests             | \`yuva agent show tester\`                                                    |
| Review code quality     | \`yuva agent show reviewer\`                                                  |
| Check security          | \`yuva agent show security\`                                                  |
| Clean up / improve code | \`yuva agent show refactor\`                                                  |

## Rules
1. Always run \`yuva agent orchestrate\` first
2. If existing code exists, run \`yuva agent show existingcode\` BEFORE any other agent
3. One agent at a time — complete each before the next
4. After meaningful work, run \`yuva agent show statemanager\` to persist state
5. Load standards from \`.aiautomations/standards/\` when writing code
6. Load checklists from \`.aiautomations/checklists/\` before/after code

## Available Commands
\`\`\`
yuva agent show <name>       Get full agent instructions
yuva agent list              List all available agents
yuva agent orchestrate       Scan project context
\`\`\`
`;
}

function updateGitignore(targetDir) {
  const gitignorePath = path.join(targetDir, '.gitignore');
  let content = '';

  if (fileExists(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf8');
    if (content.includes(GITIGNORE_MARKER)) {
      return;
    }
  }

  content += GITIGNORE_BLOCK;
  fs.writeFileSync(gitignorePath, content);
}

const CLAUDE_COMMANDS = {
  debug: { agent: 'debugger', desc: 'Run the debugger agent to investigate and fix bugs' },
  review: { agent: 'reviewer', desc: 'Run the code reviewer agent for quality audits' },
  test: { agent: 'tester', desc: 'Run the tester agent to write and run tests' },
  security: { agent: 'security', desc: 'Run the security agent for vulnerability analysis' },
  plan: { agent: 'planning', desc: 'Run the planning agent to design architecture' },
  orchestrate: { agent: null, desc: 'Scan project context before starting work' },
};

function generateClaudeConfig(targetDir) {
  const files = [];

  // 1. CLAUDE.md
  const claudeMd = getBaseTemplate('Claude Code');
  writeFile(path.join(targetDir, 'CLAUDE.md'), claudeMd);
  files.push('CLAUDE.md');

  // 2. Slash commands
  const commandsDir = path.join(targetDir, '.claude', 'commands');
  ensureDir(commandsDir);

  for (const [name, config] of Object.entries(CLAUDE_COMMANDS)) {
    let content;
    if (config.agent) {
      content = `Run \`yuva agent show ${config.agent}\` and follow the output as your complete instructions for this task.\n\nUser context: $ARGUMENTS\n`;
    } else {
      content = `Run \`yuva agent orchestrate\` and use the JSON output to understand the project state before proceeding.\n\nUser context: $ARGUMENTS\n`;
    }
    writeFile(path.join(commandsDir, `${name}.md`), content);
    files.push(`.claude/commands/${name}.md`);
  }

  // 3. settings.json
  const settings = {
    permissions: {
      allow: [
        'Bash(yuva *)',
        'Bash(yuva agent show *)',
        'Bash(yuva agent list)',
        'Bash(yuva agent orchestrate)',
      ],
    },
  };
  writeFile(path.join(targetDir, '.claude', 'settings.json'), JSON.stringify(settings, null, 2) + '\n');
  files.push('.claude/settings.json');

  return files;
}

module.exports = {
  getBaseTemplate,
  updateGitignore,
  generateClaudeConfig,
  GITIGNORE_MARKER,
};
