const path = require('path');
const fs = require('fs');
const { ensureDir, fileExists, writeFile } = require('./fs-utils');

const GITIGNORE_MARKER = '# Yuva AI - generated native configs';

const GITIGNORE_BLOCK = `
${GITIGNORE_MARKER} (regenerate with: yuva init)
# Source of truth: AGENTS.md + .aiautomations/
CLAUDE.md
.claude/
GEMINI.md
.cursor/rules/yuva-*.mdc
.windsurfrules
.github/copilot-instructions.md
.kilo/
.sourcegraph/
.amazonq/
.continue/
.aider.conf.yml
OLLAMA_INSTRUCTIONS.md
`;

function getBaseTemplate(toolName) {
  return `# Yuva AI - ${toolName} Configuration
<!-- Auto-generated by yuva init. Do not edit — regenerate with: yuva init --force -->

## CRITICAL: Before ANY task
You MUST run \`yuva agent orchestrate\` first. Do NOT start work without it.
Read the JSON output to understand the project state.

## How to load agent instructions
NEVER guess or improvise agent behavior.
Run: \`yuva agent show <name>\` to get the EXACT prompt for any agent.
Follow each agent's instructions completely before moving to the next.

## Agent Selection Guide

| User wants to...        | Run these agents in order                                                     |
|-------------------------|-------------------------------------------------------------------------------|
| Build something new     | \`yuva agent show requirements\` then \`riskassessment\` then \`planning\` then \`execution\` |
| Continue previous work  | \`yuva agent show continuity\` then resume from last point                    |
| Fix a bug / error       | \`yuva agent show debugger\`                                                  |
| Write tests             | \`yuva agent show tester\`                                                    |
| Review code quality     | \`yuva agent show reviewer\`                                                  |
| Check security          | \`yuva agent show security\`                                                  |
| Clean up / improve code | \`yuva agent show refactor\`                                                  |

## Rules
1. Always run \`yuva agent orchestrate\` first
2. If existing code exists, run \`yuva agent show existingcode\` BEFORE any other agent
3. One agent at a time — complete each before the next
4. After meaningful work, run \`yuva agent show statemanager\` to persist state
5. Load standards from \`.aiautomations/standards/\` when writing code
6. Load checklists from \`.aiautomations/checklists/\` before/after code

## Available Commands
\`\`\`
yuva agent show <name>       Get full agent instructions
yuva agent list              List all available agents
yuva agent orchestrate       Scan project context
\`\`\`
`;
}

function updateGitignore(targetDir) {
  const gitignorePath = path.join(targetDir, '.gitignore');
  let content = '';

  if (fileExists(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf8');
    if (content.includes(GITIGNORE_MARKER)) {
      return;
    }
  }

  content += GITIGNORE_BLOCK;
  fs.writeFileSync(gitignorePath, content);
}

module.exports = {
  getBaseTemplate,
  updateGitignore,
  GITIGNORE_MARKER,
};
