const path = require('path');
const fs = require('fs');
const { log, success, warn, box, info, error } = require('../colors');
const { fileExists, ensureDir, writeJSON, writeFile } = require('../fs-utils');
const { resolvePackagePath } = require('../resolve-package');
const { detectTool } = require('../detect-tool');
const { getLLMConfig } = require('../llm-adapters');

function initCommand(options = {}) {
  const targetDir = process.cwd();
  const force = options.force || false;
  const dryRun = options.dryRun || false;
  const requestedTool = options.tool || null;

  box('Yuva AI - Setup');

  // Check for existing setup
  const hasAgentsMd = fileExists(path.join(targetDir, 'AGENTS.md'));
  const hasClaudeMd = fileExists(path.join(targetDir, 'CLAUDE.md'));

  if ((hasAgentsMd || hasClaudeMd) && !force) {
    warn(`${hasAgentsMd ? 'AGENTS.md' : 'CLAUDE.md'} already exists.`);
    log('   Use --force to overwrite.\n', 'yellow');
    process.exit(1);
  }

  // Detect tool
  const tool = requestedTool || detectTool(targetDir);
  const llmConfig = getLLMConfig(tool);
  const toolName = llmConfig ? llmConfig.name : tool;

  info(`Detected AI tool: ${toolName}\n`);

  // Resolve package path
  const pkgPath = resolvePackagePath();
  if (!pkgPath) {
    error('Cannot find yuva-ai package. Try reinstalling.');
    process.exit(1);
  }

  const templatePath = path.join(pkgPath, 'template');

  if (dryRun) {
    info('DRY RUN - No files will be created.\n');
    info('Would create:');
    log(`   AGENTS.md (orchestrator for ${toolName})`);
    log('   .aiautomations/config.json');
    log('   .aiautomations/agents.md (agent index)');
    if (llmConfig && llmConfig.configFile !== 'AGENTS.md' && llmConfig.configFile !== 'CLAUDE.md') {
      log(`   ${llmConfig.configFile} (pointer to AGENTS.md)`);
    }
    return;
  }

  try {
    // 1. Copy AGENTS.md from template
    const agentsMdSrc = path.join(templatePath, 'AGENTS.md');
    if (fileExists(agentsMdSrc)) {
      fs.copyFileSync(agentsMdSrc, path.join(targetDir, 'AGENTS.md'));
    }

    // 2. Create .aiautomations/config.json
    const configDir = path.join(targetDir, '.aiautomations');
    ensureDir(configDir);

    const pkg = require(path.join(pkgPath, 'package.json'));
    const config = {
      tool: tool,
      packagePath: pkgPath,
      version: pkg.version,
      autoDetected: !requestedTool,
      telemetry: false,
      sessionPersistence: true,
    };
    writeJSON(path.join(configDir, 'config.json'), config);

    // 3. Copy agents.md index
    const agentsIndexSrc = path.join(templatePath, '.aiautomations', 'agents.md');
    if (fileExists(agentsIndexSrc)) {
      fs.copyFileSync(agentsIndexSrc, path.join(configDir, 'agents.md'));
    }

    // 4. Create tool-specific pointer file if needed
    if (llmConfig && llmConfig.configFile !== 'AGENTS.md' && llmConfig.configFile !== 'CLAUDE.md') {
      const pointerPath = path.join(targetDir, llmConfig.configFile);
      ensureDir(path.dirname(pointerPath));
      const pointerContent = [
        `# Yuva AI`,
        `<!-- Auto-generated by yuva init for ${toolName} -->`,
        `<!-- Source of truth: AGENTS.md -->`,
        ``,
        `Read and follow all instructions in the AGENTS.md file in the project root.`,
        `All agent prompts are available via: \`yuva agent show <agent-name>\``,
        `Run \`yuva agent list\` to see all available agents.`,
        `Run \`yuva agent orchestrate\` to scan project context before starting work.`,
        ``
      ].join('\n');
      writeFile(pointerPath, pointerContent);
    }

    // Success output
    success('Created files:');
    log('   AGENTS.md (orchestrator)');
    log('   .aiautomations/config.json');
    log('   .aiautomations/agents.md (agent index)');
    if (llmConfig && llmConfig.configFile !== 'AGENTS.md' && llmConfig.configFile !== 'CLAUDE.md') {
      log(`   ${llmConfig.configFile} (${toolName} pointer)`);
    }

    box('Setup Complete!', 'green');

    log(`\nConfigured for: ${toolName}`, 'bright');
    log(`Agent prompts served from: ${pkgPath}\n`);

    log('Quick start:', 'bright');
    log('  1. Open this project in your AI tool');
    log('  2. The AI reads AGENTS.md and knows how to use agents');
    log('  3. Tell it what you want to build\n');

    log('Commands:', 'bright');
    log('  yuva agent list        List all agents');
    log('  yuva agent show <name> Get agent prompt');
    log('  yuva agent orchestrate Scan project context');
    log('  yuva init <tool>       Reinitialize for different tool');
    log('  yuva doctor            Diagnose setup\n');

  } catch (err) {
    error(`Error: ${err.message}`);
    process.exit(1);
  }
}

module.exports = initCommand;
